[package]
name = "rusty-saw-view"
version = "0.8.0"
authors = ["Joseph Venetucci <venetuc@pdx.edu>"]

[dependencies]
serde = "1.0.70"
serde_json = "1.0.24"
serde_cbor = "0.8.2"
serde_derive = "1.0.70"
base64 = "0.9.2"
colored = "1.6.1"
reqwest = "0.8.6"
mockito = "0.12.0"
clap = "2.32.0"